### ISSUE TITLE
Error in Get-RemoteMachineAccountHash & Get-RemoteCachedCredential

### ISSUE THREAD

**Issue by bokandbok** [HarmJ0y/DAMP#3]
Hi, RemoteHashRetrieval.ps1 & Add-RemoteRegBackdoor work perfectly, but the other 2 functions 
Get-RemoteMachineAccountHash & Get-RemoteCachedCredential encountered some errors as shown below:

PS C:\Users\user1\Desktop\DAMP-master\DAMP-master> Get-RemoteMachineAccountHash -ComputerName mail.testdomain.com
Decrypt-AES : The parameter 'IV' cannot be specified because it conflicts with the parameter alias of the same name
for parameter 'InformationVariable'.
At C:\Users\user1\Desktop\DAMP-master\DAMP-master\RemoteHashRetrieval.ps1:1282 char:30
+     $LSAKeyStructPlaintext = Decrypt-AES -Key $TmpKey -CipherText $LS ...
+                              ~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], MetadataException
    + FullyQualifiedErrorId : ParameterNameConflictsWithAlias

Cannot index into a null array.
At C:\Users\user1\Desktop\DAMP-master\DAMP-master\RemoteHashRetrieval.ps1:1283 char:5
+     $LSAKey = $LSAKeyStructPlaintext[68..99]
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Exception calling "ToString" with "1" argument(s): "Value cannot be null.
Parameter name: value"
At C:\Users\user1\Desktop\DAMP-master\DAMP-master\RemoteHashRetrieval.ps1:1431 char:9
+         Write-Verbose ("LSA Key        : " + ([System.BitConverter]:: ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

Decrypt-AES : The parameter 'IV' cannot be specified because it conflicts with the parameter alias of the same name
for parameter 'InformationVariable'.
At C:\Users\user1\Desktop\DAMP-master\DAMP-master\RemoteHashRetrieval.ps1:1465 char:39
+         $MachineHashStructPlaintext = Decrypt-AES -Key $TempKey -Ciph ...
+                                       ~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], MetadataException
    + FullyQualifiedErrorId : ParameterNameConflictsWithAlias

Cannot index into a null array.
At C:\Users\user1\Desktop\DAMP-master\DAMP-master\RemoteHashRetrieval.ps1:1466 char:9
+         $MachineHashBytes = $MachineHashStructPlaintext[16..255]
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Multiple ambiguous overloads found for "ComputeHash" and the argument count: "1".
At C:\Users\user1\Desktop\DAMP-master\DAMP-master\RemoteHashRetrieval.ps1:1471 char:9
+         $Out = $MD4.ComputeHash($MachineHashBytes)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

Exception calling "ToString" with "1" argument(s): "Value cannot be null.
Parameter name: value"
At C:\Users\user1\Desktop\DAMP-master\DAMP-master\RemoteHashRetrieval.ps1:1472 char:9
+         $MachineAccountHash = ([System.BitConverter]::ToString($Out)  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

PS C:\Users\user1\Desktop\DAMP-master\DAMP-master> Get-RemoteCachedCredential -ComputerName mail.testdomain.com
Decrypt-AES : The parameter 'IV' cannot be specified because it conflicts with the parameter alias of the same name
for parameter 'InformationVariable'.
At C:\Users\user1\Desktop\DAMP-master\DAMP-master\RemoteHashRetrieval.ps1:1282 char:30
+     $LSAKeyStructPlaintext = Decrypt-AES -Key $TmpKey -CipherText $LS ...
+                              ~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], MetadataException
    + FullyQualifiedErrorId : ParameterNameConflictsWithAlias

Cannot index into a null array.
At C:\Users\user1\Desktop\DAMP-master\DAMP-master\RemoteHashRetrieval.ps1:1283 char:5
+     $LSAKey = $LSAKeyStructPlaintext[68..99]
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Get-RemoteNLKMKey : Cannot validate argument on parameter 'LSAKey'. The argument is null or empty. Provide an argument
that is not null or empty, and then try the command again.
At C:\Users\user1\Desktop\DAMP-master\DAMP-master\RemoteHashRetrieval.ps1:1687 char:58
+         $NLKMKey = Get-RemoteNLKMKey -hKey $nKey -LSAKey $LSAKey
+                                                          ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-RemoteNLKMKey], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Get-RemoteNLKMKey

Exception calling "ToString" with "1" argument(s): "Value cannot be null.
Parameter name: value"
At C:\Users\user1\Desktop\DAMP-master\DAMP-master\RemoteHashRetrieval.ps1:1690 char:9
+         Write-Verbose ("LSA Key        : " + ([System.BitConverter]:: ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

Exception calling "ToString" with "1" argument(s): "Value cannot be null.
Parameter name: value"
At C:\Users\user1\Desktop\DAMP-master\DAMP-master\RemoteHashRetrieval.ps1:1691 char:9
+         Write-Verbose ("NL`$KM Key     : " + ([System.BitConverter]:: ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

**Comment by ItsNee** [comment]
Did you manage to get this fixed?
